name: Test noachat.nvim
on: push

jobs:
    test:
        name: noachat.nvim test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set Up nightly Neovim
              uses: rhysd/action-setup-vim@v1
              with:
                  neovim: true
                  version: nightly

            - name: Set Up init.vim
              run: mkdir ~/.config/nvim && cp ./vimrc_test ~/.config/nvim/init.vim

            - name: check vimrc
              run: cat ~/.config/nvim/init.vim

            - name: run noachat.nvim test
              run: nvim +":call noachat#test#run()"
